### ISSUE TITLE
LEEF output for IBM QRadar

### ISSUE THREAD

**Issue by chrisforce1** [alphasoc/nfr#57]
For IBM QRadar we need to output events in LEEF format, as defined by these:

- ftp://ftp.software.ibm.com/software/security/products/qradar/documents/iTeam_addendum/b_Leef_format_guide.pdf

- https://www.ibm.com/support/knowledgecenter/SS42VS_DSM/c_LEEF_Format_Guide_predefinedAttrrs.html

The format I propose is as follows:

```Jan 18 11:07:53 nfr-host LEEF:2.0|AlphaSOC|NFR|1.0.2|<threat>|<keys and values here>```

`threat` in the above line would be the threat (e.g. `c2_communication`, `p2p_activity`, or `cryptomining`)

Regarding keys and values, we'd set the following using the LEEF standard keys:

- `devTime` and `devTimeFormat` describing the `original_event` value of the event
- `sev` is severity on a scale of 1-10 within QRadar, so we need to multiply our `severity` value by 2x
- `src` is the `src_ip` value of the client system
- `srcPort` is the `src_port` value (IP analytics events only)
- `dst` is the `dest_ip` value of the destination (IP analytics events only)
- `dstPort` is the `dest_port` value (IP analytics events only)
- `usrName` is the `src_user` value if present (username)
- `srcMAC` is the `src_mac` value if present (MAC address of the client system)
- `identHostName` is the `src_host` value if present (client system hostname)
- `srcBytes` is the `bytes_in` value if present (IP analytics events only)
- `dstBytes` is the `bytes_out` value if present (IP analytics events only)

We'd then set our own keys along with the list above, as below.

For all events:

- `description` with the title of the threat (the `ShortMessage` value we use in GELF)
- `flags` showing the list of flags associated with an event (e.g. `flags=young_domain,suspicious_tld`)
- `policy` set to `0` or `1` as we do elsewhere to show policy violations

For DNS events:

- `query` is the FQDN associated with an event (e.g. `gmail.com`)
- `recordType` is the record type associated with an event (e.g. `A`, `CNAME`, `MX`)

For IP events:

- `ja3` showing the JA3 hash for a given TLS connection event

**Comment by chrisforce1** [comment]
Here's what we should use in `config.yml` for this new output:

```
  # IBM QRadar Syslog server where AlphaSOC alerts will be sent in LEEF format
  # NFR will use TCP port 514 to send syslog messages by default. Use the
  # fields below to define the syslog server IP address and TCP port.
  qradar:
    # IP address of the QRadar Syslog TCP input
    # Default: (none)
    ip:
    # Syslog TCP port for the QRadar Syslog TCP input
    # Default: 514
    port: 514
```
